const markersFI = {
  us: {
    markers: [
      {
        id: '1',
        headline: 'Finland, the happiest country in the world, may handle coronavirus better than the US',
        color: '#FCFEC1',
        city: 'New York City',
        coordinates: [40.7128, -74.0060],
        value: 100,
        tags: '',
        code: 'US',
        date: '21 Mar 2020',
        outlet: 'Business Insider UK',
        paragraph: 'For the third year in a row, the UN has named Finland the happiest country in the world. This year, the UN said that one of the main reasons Finland ranked as the happiest country could help it deal with the challenges of the coronavirus pandemic better than other nations.',
      },
      {
        id: '2',
        headline: 'Advice from happiest nation Finland: care for each other, value learning',
        color: '#FCFEC1',
        city: 'New York City',
        coordinates: [40.7128, -74.0060],
        value: 100,
        tags: '',
        code: 'US',
        date: '20 Mar 2020',
        outlet: 'Reuters',
        paragraph: 'Advice from the happiest country - give all your kids the best possible education and care for each other and the environment, especially at this time of global crisis caused by the coronavirus epidemic.',
      },
      {
        id: '3',
        headline: 'Finland Cuts Off Helsinki Region In Coronavirus Clampdown',
        color: '#FCFEC1',
        city: 'New York City',
        coordinates: [40.7128, -74.0060],
        value: 100,
        tags: '',
        code: 'US',
        date: '25 Mar 2020',
        outlet: 'Forbes',
        paragraph: 'Finland has already closed its borders to non-residents, closed schools and limited public gatherings to a maximum of 10 people in a bid to slow the spread of the novel coronavirus COVID-19.',
      },
      {
        id: '4',
        headline: 'Finland Invokes Emergency Powers to Slow Coronavirus Spread',
        color: '#FCFEC1',
        city: 'New York City',
        coordinates: [40.7128, -74.0060],
        value: 100,
        tags: '',
        code: 'US',
        date: '16 Mar 2020',
        outlet: 'Bloomberg',
        paragraph: 'Finland government is preparing to invoke emergency powers to combat the spread of the novel coronavirus.',
      },
      {
        id: '5',
        headline: 'Finnish health boss questions WHO coronavirus testing advice',
        color: '#FCFEC1',
        city: 'New York City',
        coordinates: [40.7128, -74.0060],
        value: 100,
        tags: '',
        code: 'US',
        date: '20 Mar 2020',
        outlet: 'Reuters',
        paragraph: 'Finland national health authority questioned on Friday the World Health Organization call on countries to test as many patients as possible for coronavirus.',
      },
    ]
  },
  ca: {
    markers: [
      {
        id: '1',
        headline: 'Finland, the happiest country in the world, may handle coronavirus better than the US',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '21 Mar 2020',
        outlet: 'Business Insider UK',
        paragraph: 'For the third year in a row, the UN has named Finland the happiest country in the world. This year, the UN said that one of the main reasons Finland ranked as the happiest country could help it deal with the challenges of the coronavirus pandemic better than other nations.',
      },
      {
        id: '2',
        headline: 'Finland Cuts Off Helsinki Region In Coronavirus Clampdown',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '25 Mar 2020',
        outlet: 'Forbes',
        paragraph: 'Finland has already closed its borders to non-residents, closed schools and limited public gatherings to a maximum of 10 people in a bid to slow the spread of the novel coronavirus COVID-19.',
      },
      {
        id: '3',
        headline: 'Finland Invokes Emergency Powers to Slow Coronavirus Spread',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '16 Mar 2020',
        outlet: 'Bloomberg',
        paragraph: 'Finland government is preparing to invoke emergency powers to combat the spread of the novel coronavirus.',
      },
      {
        id: '4',
        headline: 'Finland lowers bank buffers in coronavirus response, prepares to close borders',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '17 Mar 2020',
        outlet: 'National Post',
        paragraph: 'Finland decided late on Tuesday to lower buffer requirements of its banks, attempting to boost the slowing economy, as the country prepared to close its borders as part of the response to slow the spread of the coronavirus.',
      },
      {
        id: '5',
        headline: 'Finland to ban public meetings of more than 500 due to coronavirus',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '12 Mar 2020',
        outlet: 'National Post',
        paragraph: 'Finland will ban public meetings of more than 500 people until the end of May due to the coronavirus outbreak, Prime Minister Sanna Marin said on Thursday.',
      },

    ]
  },
  be: {
    markers: [
      {
        id: '1',
        headline: 'Finland, the happiest country in the world, may handle coronavirus better than the US',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '21 Mar 2020',
        outlet: 'Business Insider UK',
        paragraph: 'For the third year in a row, the UN has named Finland the happiest country in the world. This year, the UN said that one of the main reasons Finland ranked as the happiest country could help it deal with the challenges of the coronavirus pandemic better than other nations.',
      },
      {
        id: '2',
        headline: 'Finland Cuts Off Helsinki Region In Coronavirus Clampdown',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '25 Mar 2020',
        outlet: 'Forbes',
        paragraph: 'Finland has already closed its borders to non-residents, closed schools and limited public gatherings to a maximum of 10 people in a bid to slow the spread of the novel coronavirus COVID-19.',
      },
      {
        id: '3',
        headline: 'Finland former president has coronavirus',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '24 Mar 2020',
        outlet: 'EUobserver',
        paragraph: 'Finland´ former president, Martti Ahtisaari, has been diagnosed with coronavirus, according to a statement from the office of the president.',
      },
      {
        id: '4',
        headline: 'Finland Invokes Emergency Powers to Slow Coronavirus Spread',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '16 Mar 2020',
        outlet: 'Bloomberg',
        paragraph: 'Finland government is preparing to invoke emergency powers to combat the spread of the novel coronavirus.',
      },
      {
        id: '5',
        headline: 'Finland install further measures to prevent the spread of the coronavirus',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '27 Mar 2020',
        outlet: 'ScandAsia.com',
        paragraph: 'Nationwide, Finland has confirmed 880 cases of COVID-19 and three deaths: the spread of the virus is further along in the region of Uusimaa.',
      },
    ]
  },
}

export { markersFI }