const markersUS = {
  dk: {
    markers: [
      {
        id: '1',
        headline: 'US has restricted travel to and from these countries amid coronavirus pandemic',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '11 Mar 2020',
        outlet: 'FOX News',
        paragraph: 'The Trump administration will suspend travel between European countries and the United States for 30 days.',
      },
      {
        id: '2',
        headline: 'Huge corona scandal rising in US: While calming the population, he sold his shares',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '22 Mar 2020',
        outlet: 'TV 2',
        paragraph: 'More than two dozen congressmen are accused of insider trading before the corona crisis hit the United States.',
      },
      {
        id: '3',
        headline: 'David Trads: Bizarre coronakaos may end with Trump’s re-election',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '26 Mar 2020',
        outlet: 'Altinget.dk',
        paragraph: 'll analyzes and forecasts made about the outcome of the November US election should now be thrown down the board. Now it’s all about handling corona.',
    },
      {
        id: '4',
        headline: 'Trump’s travel ban puts stocks and oil prices in the bottom',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '12 Mar 2020',
        outlet: 'Ekstra Bladet',
        paragraph: 'It could be felt in Asian stock markets that Trump announced a travel ban from Europe to the US',
      },
      {
        id: '5',
        headline: 'David Trads: Trump is disastrous. We need Churchill',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '17 Mar 2020',
        outlet: 'Altinget.dk',
        paragraph: 'We can’t just hope that Trump and the United States take the global leadership in the war we are fighting against the damned virus.',
      },
    ]
  },
  fi: {
    markers: [
      // VPN: FINLAND
      {
        id: '1',
        headline: 'The United States now has the highest number of coronavirus infections in the world',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '27 Mar 2020',
        outlet: 'Helsingin Sanomat',
        paragraph: 'How did the country slip into error one point at a time?',
      },
      {
        id: '2',
        headline: 'Trump bans travel from 26 European countries to the USA because of the coronavirus, Finland is among them',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '12 Mar 2020',
        outlet: 'Helsingin Sanomat',
        paragraph: 'Restrictions will be adjusted according to circumstances, the president said of the White House.',
      },
      {
        id: '3',
        headline: 'The United States is cutting its aid to Afghanistan by a billion - the reason for the country’s political impasse',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '24 Mar 2020',
        outlet: 'YLE',
        paragraph: 'The coronavirus is slowing the withdrawal agreed with the Taliban.',
      },
      {
        id: '4',
        headline: 'In the US, half of working-age people in the intensive care unit',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '19 Mar 2020',
        outlet: 'Helsingin Sanomat',
        paragraph: 'Statistics shatter perception of coronary heart disease, which is mostly dangerous for the elderly.',
      },
      {
        id: '5',
        headline: 'The number of coronary infections in the US quadrupled in two days - the rate in California is even more incomprehensible',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '20 Mar 2020',
        outlet: 'Iltalehti',
        paragraph: 'In the United States, the coronavirus is spreading rapidly.',
      },
    ]
  },
  ie: {
    markers: [
      {
        id: '1',
        headline: 'Irish citizens on cruise ship’ with 21 coronavirus cases',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '7 Mar 2020',
        outlet: 'RTÉ',
        paragraph: 'More than 200 people have contracted the virus in the United States, and 12 have died, 11 of them in the state of Washington.',
      },
      {
        id: '2',
        headline: 'US coronavirus death toll rises as Chinese cases fall',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '2 Mar 2020',
        outlet: 'RTÉ',
        paragraph: 'The death toll from the new coronavirus in the United States has climbed to six.',
      },
      {
        id: '3',
        headline: 'US extends travel ban to Ireland, UK over coronavirus',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '14 Mar 2020',
        outlet: 'RTÉ',
        paragraph: 'The ban will come into effect at 4am (Irish time) on Tuesday.',
      },
      {
        id: '4',
        headline: 'Trump declares Covid-19 travel ban from most of Europe, excluding Ireland and UK',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '12 Mar 2020',
        outlet: 'RTÉ',
        paragraph: 'US President Donald Trump has announced the suspension of all travel to the United States from the majority of European nations for 30 days.',
      },
      {
        id: '5',
        headline: 'Tom Hanks Got Sick in Australia, Where Coronavirus Testing Isn’t Such a Hassle',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '12 Mar 2020',
        outlet: 'The New York Times',
        paragraph: 'In the United States, little if anything about the testing has been efficient or convenient.',
      },

    ]
  },
}

export { markersUS }